import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import java.time.Duration;
import java.time.Instant;

/*
    This program was made and coded by Jesse Jones
    On June 10th, 2024
    To create a Rock Paper Scissors game for children to enjoy
*/

public class MainProgram extends javax.swing.JFrame {

    // Global variables
    private String[] choices = {"rock", "paper", "scissors"};
    private Random random = new Random();
    private int playerWins = 0;
    private int computerWins = 0;
    private int playerTotalScore = 0;
    private int roundsPlayed = 0;
    private static final int MAX_ROUNDS = 5;
    private static final String HIGH_SCORE_FILE = "highscore.txt";
    private String[] playerChoices = new String[MAX_ROUNDS];
    private String[] computerChoices = new String[MAX_ROUNDS];
    private  String[] roundResults = new String[MAX_ROUNDS];
    private int highScore = 0;
    private Instant startTime;
    
    public MainProgram() {
        initComponents();
        
        getRootPane().setDefaultButton(playButton);  // Enter now triggers "Shoot!"
        
        // Load the high score when the program starts
        loadHighScore();
        
        // Display the high score in the scoreTextField
        scoreTextField.setText("High Score: " + highScore);
    }

    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoLabel = new javax.swing.JLabel();
        rpcTextField = new javax.swing.JTextField();
        scoreTextField = new javax.swing.JTextField();
        outputScroll = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        scroll2 = new javax.swing.JScrollPane();
        standOutArea = new javax.swing.JTextArea();
        playButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        tryAgainButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoLabel.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(0, 153, 255));
        infoLabel.setText("Enter 'Rock', 'Paper' or 'Scissors':");
        getContentPane().add(infoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        rpcTextField.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        getContentPane().add(rpcTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 230, -1));

        scoreTextField.setEditable(false);
        scoreTextField.setFont(new java.awt.Font("Lucida Bright", 1, 10)); // NOI18N
        scoreTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        scoreTextField.setEnabled(false);
        getContentPane().add(scoreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 150, 30));

        outputArea.setEditable(false);
        outputArea.setColumns(20);
        outputArea.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        outputArea.setRows(5);
        outputArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        outputArea.setEnabled(false);
        outputScroll.setViewportView(outputArea);

        getContentPane().add(outputScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 470, 230));

        scroll2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scroll2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scroll2.setEnabled(false);
        scroll2.setFocusable(false);
        scroll2.setHorizontalScrollBar(null);
        scroll2.setRequestFocusEnabled(false);
        scroll2.setVerifyInputWhenFocusTarget(false);
        scroll2.setWheelScrollingEnabled(false);

        standOutArea.setEditable(false);
        standOutArea.setColumns(20);
        standOutArea.setRows(5);
        standOutArea.setAutoscrolls(false);
        standOutArea.setEnabled(false);
        standOutArea.setFocusable(false);
        standOutArea.setRequestFocusEnabled(false);
        standOutArea.setVerifyInputWhenFocusTarget(false);
        scroll2.setViewportView(standOutArea);

        getContentPane().add(scroll2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 330, 90));

        playButton.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        playButton.setForeground(new java.awt.Color(51, 51, 255));
        playButton.setText("Shoot!");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        getContentPane().add(playButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 330, -1));

        backButton.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(51, 204, 0));
        backButton.setText("Go Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 110, -1));

        exitButton.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(204, 0, 0));
        exitButton.setText("Exit Game");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 110, -1));

        tryAgainButton.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        tryAgainButton.setForeground(new java.awt.Color(51, 204, 0));
        tryAgainButton.setText("Try Again");
        tryAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryAgainButtonActionPerformed(evt);
            }
        });
        getContentPane().add(tryAgainButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 110, 30));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.png"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // Closes program
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // Takes user back to previous page
        close();
        RpsForm rps = new RpsForm();
        rps.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        // Refocuses on text box so player can type again without having to click the box.
        rpcTextField.requestFocusInWindow();

        // Clearing previous output
        outputArea.setText("");

        // Initiating values
        String rpcInput = (rpcTextField.getText()).trim().toLowerCase();
        String computerChoice = generateComputerChoice();
        
        if (rpcInput.isEmpty()) {
            outputArea.setText("Input is empty. Please enter 'rock', 'paper' or 'scissors'.");
            rpcTextField.setText("");
            return;
        }
        
        // Check user input for 'rock' 'paper' or 'scissors'
        if (!rpcInput.equals("rock") && !rpcInput.equals("paper") && !rpcInput.equals("scissors")) {
            outputArea.setText("Invalid choice! Please enter 'rock', 'paper', or 'scissors'.");
            rpcTextField.setText("");
            return;
        }
        
        // Start timer if it's the first round
        if (startTime == null) {
            startTime = Instant.now();
        }
        
        // Output choices
        outputArea.append("Round " + (roundsPlayed + 1) + ":\n");
        outputArea.append("You chose: " + rpcInput + "\n");
        outputArea.append("Computer chose: " + computerChoice + "\n");
        
        // Store choices for this round
        playerChoices[roundsPlayed] = rpcInput;
        computerChoices[roundsPlayed] = computerChoice;
        
        // Increment the number of rounds played
        roundsPlayed++;
        
        // Determine the result
        if (rpcInput.equals(computerChoice)) {
            roundsPlayed--;
            outputArea.append("It's a tie! Enter your choice and play another round.\n\n");
            roundResults[roundsPlayed] = "Tie";
        } else if ((rpcInput.equals("rock") && computerChoice.equals("scissors")) || (rpcInput.equals("paper") && computerChoice.equals("rock")) || (rpcInput.equals("scissors") && computerChoice.equals("paper"))) {
            outputArea.append("You win!\n\n");
            playerWins++;
            roundResults[roundsPlayed - 1] = "Player wins";
        } else {
            outputArea.append("You lose!\n\n");
            computerWins++;
            roundResults[roundsPlayed - 1] = "Computer wins";
        }
        
        // Check if best out of 5 has been reached
        if (roundsPlayed >= MAX_ROUNDS) {
            // Calculate total game duration
            Instant endTime = Instant.now();
            long gameDurationMillis = Duration.between(startTime, endTime).toMillis();
            
            // Calculate time bonus based on game duration
            int timeBonus = calculateTimeBonus(gameDurationMillis);
            
            // Update player score with time bonus
            playerTotalScore = playerWins * 500;
            if (playerWins > computerWins) {
                playerTotalScore += timeBonus;
            }
            
            // Update scores and win counts
            outputArea.append("Player Wins: " + playerWins + " | Player Score: " + playerTotalScore + "\nComputer Wins: " + computerWins);
            
            // Check for high score
            if (playerTotalScore > highScore) {
                highScore = playerTotalScore;
                saveHighScore();
                scoreTextField.setText("New High Score: " + highScore);
            } else {
                scoreTextField.setText("High Score: " + highScore);
            }
            
            // Check game outcome
            if (playerWins > computerWins) {
                outputArea.append("\n\nGame Over! You won the game with " + playerWins + " wins! \nEnter your choice again to start another game.");
            } else if (computerWins > playerWins) {
                outputArea.append("\n\nGame Over! The computer won the game with " + computerWins + " wins. \nEnter your choice again to start another game.");
            }
            
            // Display round details
            displayRoundDetails(playerChoices, computerChoices, roundResults);
            
            // Reset rounds played and other game variables for next game
            resetGame();
        }
        
        // Clears input
        rpcTextField.setText("");
    }//GEN-LAST:event_playButtonActionPerformed

    private void tryAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryAgainButtonActionPerformed
        // Reset the current game but keep the high score
        resetGame();

        // Reset the screen
        outputArea.setText("");
        rpcTextField.setText("");
        scoreTextField.setText("High Score: " + highScore);
        rpcTextField.requestFocusInWindow();
    }//GEN-LAST:event_tryAgainButtonActionPerformed

    private String generateComputerChoice() {
        int comIndex = random.nextInt(choices.length);
        return choices[comIndex];
    }
    
    // Method to display round details
    private void displayRoundDetails(String[] playerChoices, String[] computerChoices, String[] roundResults) {
        outputArea.append("\n\nRound Details:\n");

        for (int i = 0; i < playerChoices.length; i++) {
            outputArea.append("Round " + (i + 1) + ": ");
            outputArea.append("You chose " + playerChoices[i] + ", ");
            outputArea.append("Computer chose " + computerChoices[i] + ", ");
            outputArea.append("Result: " + roundResults[i] + "\n");
        }
    }
    
    // Method to calculate time bonus based on total game duration
    private int calculateTimeBonus(long gameDurationMillis) {
        int baseScore = 3000; // Base score
        int timeFactor = 70; // Time factor
        
        // Calculate bonus based on game duration
        int timeBonus = (int) (baseScore - (gameDurationMillis / timeFactor));
        
        return Math.max(0, timeBonus); // Ensure time bonus is non-negative
    }
    
    // Load high score from file
    private void loadHighScore() {
        try (BufferedReader reader = new BufferedReader(new FileReader(HIGH_SCORE_FILE))) {
            highScore = Integer.parseInt(reader.readLine());
        } catch (IOException | NumberFormatException e) {
            highScore = 0;
        }
    }
    
    // Save high score to file
    private void saveHighScore() {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(HIGH_SCORE_FILE))) {
            writer.write(String.valueOf(highScore));
        } catch (IOException e) {
            outputArea.append("\nCan't write to external file.");
        }
    }
    
    private void resetGame() {
        roundsPlayed = 0;
        playerWins = 0;
        computerWins = 0;
        playerTotalScore = 0;
        startTime = null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JScrollPane outputScroll;
    private javax.swing.JButton playButton;
    private javax.swing.JTextField rpcTextField;
    private javax.swing.JTextField scoreTextField;
    private javax.swing.JScrollPane scroll2;
    private javax.swing.JTextArea standOutArea;
    private javax.swing.JButton tryAgainButton;
    // End of variables declaration//GEN-END:variables
}
