import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/*
    This program was made and coded by Jesse Jones
    On June 10th
    To create a Rock Paper Scissors game for children to enjoy
*/
public class rpsForm extends javax.swing.JFrame {

    /**
     * Creates new form rpsForm
     */
    public rpsForm() {
        initComponents();
    }

    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        explainLabel1 = new javax.swing.JLabel();
        explainLabel2 = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        backgroundArea = new javax.swing.JTextArea();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        explainLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        explainLabel1.setForeground(new java.awt.Color(102, 102, 255));
        explainLabel1.setText("Play best out of 5 against the computer.");
        getContentPane().add(explainLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        explainLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        explainLabel2.setForeground(new java.awt.Color(102, 102, 255));
        explainLabel2.setText("Try and beat your highest score!");
        getContentPane().add(explainLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo.png"))); // NOI18N
        getContentPane().add(iconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 260, 210));

        startButton.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        startButton.setForeground(new java.awt.Color(51, 51, 255));
        startButton.setText("START");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 360, 30));

        exitButton.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 0, 0));
        exitButton.setText("Exit Game");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 360, 30));

        scroll.setEnabled(false);

        backgroundArea.setEditable(false);
        backgroundArea.setColumns(20);
        backgroundArea.setRows(5);
        backgroundArea.setAutoscrolls(false);
        backgroundArea.setEnabled(false);
        scroll.setViewportView(backgroundArea);
        backgroundArea.getAccessibleContext().setAccessibleParent(null);

        getContentPane().add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 360, 300));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.png"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // Closes the title screen and opens the game window
        close();
        mainProgram mp = new mainProgram();
        mp.setVisible(true);
    }//GEN-LAST:event_startButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // Closes program
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rpsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rpsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rpsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rpsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rpsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea backgroundArea;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel explainLabel1;
    private javax.swing.JLabel explainLabel2;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
